### PR TITLE
Fixed an opcode for "gorci" instruction

### PR DESCRIPTION
**Pull request by pr0kuk**

### CODE REVIEW

**Comment by pavelkryukov** [comment]
Could you please tell if you can reproduce that issue locally?
What is the build command you are using?

**Comment by pr0kuk** [comment]
I haven't built this on my pc but this is only one string. It should work ok.

**Comment by pavelkryukov** [comment]
> I haven't built this on my pc

Why? If you have an issue with environment, please explain it.

> It should work ok.

No, it does not. Why do you think it should work? We have tests to check if something works or not.

As a project maintainer, I expect every proposed line to be responsibly written, even it is a single line.

**Comment by pr0kuk** [comment]
> Could you please tell if you can reproduce that issue locally?
> What is the build command you are using?

I ran it locally and got the same error - overspecified.
And I actually can't imagine where the overspecification might come from.
Because gorci consists of rd, rs1, imm20
And according to specification 
| 00101 | imm | rs1 | 101 | rd | 0010011 | GORCI
Bits from 31 to 27 is 0x5
Bits from 26 to 20 is imm20
Bits from 19 to 15 is rs1
Bits from 14 to 12 is 5
Bits from 11 to 7 is rd
Bits from  6 to 2 is 0x4
And last 2 bits is 3

**Comment by pavelkryukov** [comment]
`imm20` is used for 20 bits immediates (31..12)

https://github.com/MIPT-ILab/riscv-opcodes/blob/114bd42115516758d1664853233f499e4620117b/parse_opcodes#L28

For (26..20). `shamt` should work:

https://github.com/MIPT-ILab/riscv-opcodes/blob/114bd42115516758d1664853233f499e4620117b/parse_opcodes#L36

In specification, `groci` is similar to `slli`, which is encoded with `shamt`:

https://github.com/MIPT-ILab/riscv-opcodes/blob/114bd42115516758d1664853233f499e4620117b/opcodes-rv32i#L25

**Comment by pr0kuk** [comment]
Thank you a lot, it helped

**Review by pavelkryukov — APPROVED** [review]

**Comment by pavelkryukov** [comment]
Thanks. Now please update submodule in you repository and check if MIPT-V tests pass with new instruction.

**Pull request merged**
